  version: '3'

  services:
    db:
      image: postgres:11
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      image: busprix
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
    migration:
      image: busprix
      command: python manage.py migrate --noinput
      volumes:
        - .:/code
      depends_on:
        - db