version: '3.1'

services:

  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: busbprix
    volumes:
    - postgress:/var/lib/postgresql/data


  webapp:
    build: .
    ports:
     - "8000:8000"
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - postgres


volumes:
  postgress:
