# Generated by Django 3.1 on 2020-08-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
