# Generated by Django 3.1 on 2020-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200817_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('email', models.CharField(db_index=True, max_length=200)),
                ('topic', models.CharField(db_index=True, max_length=200)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='main',
        ),
    ]
