# Generated by Django 3.1 on 2020-08-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200818_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=200, verbose_name='Номер телефона')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Ваш email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, verbose_name='Ваше сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Тема сообщения'),
        ),
    ]
