# Generated by Django 3.1 on 2020-09-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200824_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Ваше имя')),
                ('comment', models.TextField(blank=True, verbose_name='Ваше сообщение')),
                ('number', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=200, verbose_name='Ваш email'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
