# Generated by Django 3.0.8 on 2020-07-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200726_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='slug',
            field=models.SlugField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
