# Generated by Django 3.0.8 on 2020-07-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_productimage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='slug',
        ),
    ]
