# Generated by Django 3.0.8 on 2020-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_productimage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rear_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='side_image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
