# Generated by Django 3.0.8 on 2020-08-03 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
    ]
