# Generated by Django 3.0.8 on 2020-08-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_product_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rear_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_image',
        ),
    ]
