# Generated by Django 3.0.8 on 2020-08-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200804_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.CharField(default=None, max_length=50, verbose_name='Примечание (№ отделения, Новая почта/Укр.почта т.д.)'),
        ),
    ]
