# Generated by Django 3.0.8 on 2020-08-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200804_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, verbose_name='Номер телефона'),
        ),
    ]
